network:
        version: 2
        renderer: networkd
        ethernets:
                eth0:
                  optional: true
                  dhcp4: true
                usb0:
                  dhcp4: false
                  optional: true
                  addresses: [10.55.0.1/29]
        wifis:
             wlan0:
                optional: true
                dhcp4: true
                access-points:
                        "L5GLB_Ext":
                                password: "password"
                        "YYDS":
                                password: "password"
                        tusecurewireless:
                                auth:
                                   key-management: eap
                                   password: hash:1df3e3e2a1d6aace8451df53e5c8c429
                                   method: peap
                                   identity: lbai
